#!/usr/bin/env python3
"""Generate glossary term pages - Batch 2 (17 terms)."""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from glossary_batch1 import generate_page

SITE_ROOT = "/Users/rome/Documents/projects/verum-website"
GLOSSARY_DIR = os.path.join(SITE_ROOT, "glossary")

TERMS = [
    {
        "slug": "data-quality-management",
        "term": "Data Quality Management",
        "meta_desc": "Data quality management is the discipline of measuring, monitoring, and improving data accuracy across your organization. Learn the key dimensions and how to build a program.",
        "definition": '<p><strong>Data quality management (DQM)</strong> is the ongoing discipline of measuring, monitoring, and improving the accuracy, completeness, consistency, and timeliness of data across your business systems. It combines technology, processes, and people to ensure that the data driving your decisions is actually reliable. DQM isn\'t a one-time project. It\'s a continuous practice.</p>',
        "why_matters": "<p>Bad data costs U.S. businesses an estimated $3.1 trillion per year according to IBM. For a typical mid-market B2B company, that translates to misrouted leads, wasted ad spend, inaccurate forecasts, and failed integrations. Teams that treat data quality as someone else's problem end up with a CRM nobody trusts, reports nobody believes, and automation that breaks in production.</p>",
        "how_heading": "The Five Dimensions of Data Quality",
        "how_items": [
            ("Accuracy", "Does the data reflect reality? Is the email address current? Is the job title correct? Accuracy is the most important dimension because everything downstream depends on it"),
            ("Completeness", "Are required fields filled in? A contact with a name but no email and no phone is incomplete and unusable for outreach"),
            ("Consistency", "Is data formatted the same way everywhere? If marketing uses 'Software' and sales uses 'SaaS,' your segments won't work"),
            ("Timeliness", "Is the data current? A record updated 2 years ago has probably decayed. Freshness matters for B2B data"),
            ("Uniqueness", "Does each entity appear only once? Duplicates inflate counts and create conflicting information"),
        ],
        "example": "<p>A VP of Sales notices that 30% of leads assigned to the West Coast team are actually East Coast companies. Investigation reveals the 'State' field has no validation rules. Reps type whatever they want. DQM fix: add picklist validation, clean existing data, and monitor for drift. Lead routing accuracy jumps from 70% to 98%.</p>",
        "related_terms": [("Data Governance", "data-governance"), ("Data Hygiene", "data-hygiene"), ("Data Profiling", "data-profiling")],
        "related_resources": [("Data Quality Metrics", "/resources/data-quality-metrics.html"), ("Data Quality Roadmap", "/resources/data-quality-roadmap.html"), ("Data Quality Assessment", "/assessment/")],
        "cta_headline": "Need a data quality baseline?",
        "cta_text": "We'll audit your database, measure quality across all five dimensions, and give you a prioritized fix list.",
    },
    {
        "slug": "data-standardization",
        "term": "Data Standardization",
        "meta_desc": "Data standardization converts data into consistent formats so records can be compared, merged, and analyzed. Learn what fields need standardizing and why it matters.",
        "definition": '<p><strong>Data standardization</strong> converts data values into consistent, predefined formats so that records can be accurately compared, merged, and analyzed. It covers everything from capitalizing names correctly (john doe becomes John Doe) to normalizing job titles (VP Sales, Vice President of Sales, and VP-Sales all become Vice President of Sales). Without standardization, the same data looks different enough that your systems treat it as different records.</p>',
        "why_matters": "<p>Inconsistent data breaks everything downstream. Deduplication can't match \"Acme Corp\" to \"ACME Corporation\" if they're not standardized first. Lead routing fails when \"California\" and \"CA\" and \"Calif\" map to different territories. Reports show fragmented data instead of aggregated totals. Standardization is the foundation that makes every other data operation work correctly.</p>",
        "how_heading": "What Gets Standardized",
        "how_items": [
            ("Company names", "Acme Corp, ACME Inc., Acme Corporation all become the canonical form. Legal suffixes (LLC, Inc.) are standardized or stripped"),
            ("Job titles", "VP Sales, Vice President of Sales, VP - Sales all normalize to a standard title and seniority level"),
            ("Phone numbers", "Convert all formats to E.164 standard (+16125551234) with a display format alongside"),
            ("Addresses", "USPS Publication 28 standards for US addresses. Street/St/Str/Ave all get consistent abbreviations"),
            ("Industry and category", "Map free-text industry entries to standard classifications like NAICS or SIC codes"),
        ],
        "example": "<p>A company exports 30,000 contacts and finds the \"State\" field contains CA, California, Calif, Cali, and Ca. The \"Title\" field has 4,200 unique values for 30,000 records. After standardization, states map to 50 valid two-letter codes and titles collapse to 340 normalized values. Segmentation and routing that was broken now works.</p>",
        "related_terms": [("Data Normalization", "data-normalization"), ("Data Governance", "data-governance"), ("Data Quality Management", "data-quality-management")],
        "related_resources": [("Data Standardization Service", "/cleaning/data-standardization/"), ("Job Title Normalization", "/cleaning/job-title-normalization/"), ("Company Name Standardization", "/cleaning/company-name-standardization/")],
        "cta_headline": "Inconsistent data everywhere?",
        "cta_text": "We'll standardize your entire database so every field uses the same format, every time.",
    },
    {
        "slug": "data-validation",
        "term": "Data Validation",
        "meta_desc": "Data validation checks whether data meets defined rules for format, range, and accuracy. Learn the types of validation and when to apply each one.",
        "definition": '<p><strong>Data validation</strong> checks whether data meets predefined rules for format, type, range, and accuracy before it enters your system or gets used in a process. It catches problems at the point of entry: Is this a valid email format? Does this ZIP code exist? Is this phone number the right length? Validation is your first line of defense against bad data getting into your database.</p>',
        "why_matters": "<p>Cleaning data after it's in your system is 10x more expensive than catching it on the way in. A validation rule that rejects \"jsmith@gmial.com\" saves the downstream work of identifying the bounce, flagging the record, researching the correct address, and updating it. Multiply that by thousands of records and validation becomes one of the highest-ROI data quality investments you can make.</p>",
        "how_heading": "Types of Data Validation",
        "how_items": [
            ("Format validation", "Check that emails have an @ and domain, phone numbers have correct digit counts, ZIP codes are 5 or 9 digits"),
            ("Range validation", "Employee count should be positive. Revenue should be within reasonable bounds. Dates should be in the past for founding years"),
            ("Referential validation", "Does this state+ZIP combination actually exist? Does the area code match the stated location?"),
            ("Cross-field validation", "If country is 'US,' the phone should start with +1. If the role is 'CEO,' seniority shouldn't be 'Junior'"),
            ("Real-time verification", "Check email deliverability, phone connectivity, and address existence against live databases"),
        ],
        "example": "<p>A company adds validation rules to their web forms: email format check, phone length check, and company name required. They also run nightly validation on CRM imports. Invalid records go to a review queue instead of entering the database directly. After three months, the percentage of records requiring manual cleanup drops from 25% to 4%.</p>",
        "related_terms": [("Email Validation", "email-validation"), ("Address Validation", "address-validation"), ("Data Quality Management", "data-quality-management")],
        "related_resources": [("Data Validation Service", "/cleaning/data-validation/"), ("Pre-Import Validation", "/validation/pre-import-validation/"), ("Batch Validation", "/validation/batch-validation/")],
        "cta_headline": "Bad data getting into your CRM?",
        "cta_text": "We'll validate your existing records and help you set up rules to prevent bad data from entering in the first place.",
    },
    {
        "slug": "demand-generation",
        "term": "Demand Generation",
        "meta_desc": "Demand generation creates awareness and interest in your product across your target market. Learn how it differs from lead gen and why data quality fuels it.",
        "definition": '<p><strong>Demand generation</strong> is the marketing discipline of creating awareness, interest, and pipeline for your product across your total addressable market. Unlike lead generation, which focuses on capturing contact information from people already interested, demand generation creates the interest in the first place. It includes content marketing, events, advertising, partner programs, and brand building.</p>',
        "why_matters": "<p>Demand gen programs live or die on data quality. If your target account list is wrong, your ads reach the wrong companies. If your contact data is outdated, your nurture emails bounce. If your firmographic data is incomplete, your segmentation groups the wrong accounts together. The creative might be brilliant, but if it's delivered to the wrong audience, it generates zero demand.</p>",
        "how_heading": "How Data Powers Demand Generation",
        "how_items": [
            ("Audience building", "Build target account lists using firmographic, technographic, and intent data to reach companies that fit your ICP"),
            ("Personalized advertising", "Use enriched data to run account-based ads on LinkedIn and display networks, targeting by company, title, and industry"),
            ("Content targeting", "Match content topics to where prospects are in the buying journey based on their engagement data"),
            ("Lead scoring", "Score inbound leads based on enriched firmographic data to separate high-fit from low-fit immediately"),
            ("Attribution", "Track which channels and campaigns generated qualified pipeline, not just leads"),
        ],
        "example": "<p>A B2B company enriches their target account list with tech stack data and discovers that 40% of their market uses a competitor product. They build a campaign specifically for competitive displacement, referencing the competitor by name in ads and emails. Pipeline from this segment is 4x higher than generic campaigns.</p>",
        "related_terms": [("Account-Based Marketing (ABM)", "abm"), ("Lead Scoring", "lead-scoring"), ("Buyer Intent Data", "buyer-intent-data")],
        "related_resources": [("Campaign Targeting", "/use-cases/campaign-targeting/"), ("SMB Targeting", "/use-cases/smb-targeting/"), ("Data Enrichment Services", "/services/data-enrichment.html")],
        "cta_headline": "Need better targeting data?",
        "cta_text": "We'll build and enrich your target account list so your demand gen campaigns reach the right companies.",
    },
    {
        "slug": "duplicate-detection",
        "term": "Duplicate Detection",
        "meta_desc": "Duplicate detection identifies records in your database that represent the same person or company. Learn matching techniques and how to prevent duplicates.",
        "definition": '<p><strong>Duplicate detection</strong> identifies records in your database that represent the same person, company, or entity. It goes beyond exact matching (same email = same person) to fuzzy matching that catches near-duplicates: "Robert Smith" vs "Bob Smith," "Acme Corp" vs "Acme Corporation," or two records with different emails but the same phone number. Detection is the first step; merging or resolving the duplicates is the second.</p>',
        "why_matters": "<p>The average CRM contains 10-25% duplicate records. Every duplicate means reps might call the same person twice, marketing sends redundant emails, pipeline reports are inflated, and customer 360 views are fragmented. One company discovered their pipeline was overstated by $2M because 400 opportunities were duplicated across territories. Duplicates also break automation: a lead enters two nurture streams simultaneously and gets conflicting messages.</p>",
        "how_heading": "Detection Techniques",
        "how_items": [
            ("Exact matching", "Compare emails, phone numbers, or other unique identifiers for identical values"),
            ("Fuzzy name matching", "Use algorithms like Levenshtein distance, Soundex, or Jaro-Winkler to catch spelling variations and nicknames"),
            ("Company normalization", "Standardize company names before matching so 'Acme Inc' and 'ACME Corporation' get caught"),
            ("Cross-field matching", "Different email but same phone? Different name but same LinkedIn URL? Match across multiple fields for higher confidence"),
            ("Confidence scoring", "Score each potential match. Auto-merge high-confidence pairs and flag low-confidence for human review"),
        ],
        "example": '<p>A database scan of 60,000 contacts finds 7,200 potential duplicate pairs. 4,800 are high-confidence (same email or phone) and merge automatically. 2,400 are medium-confidence (similar name + same company) and go to a review queue. An analyst confirms 1,900 are real duplicates and rejects 500 that are different people with similar names.</p>',
        "related_terms": [("Data Deduplication", "data-deduplication"), ("Fuzzy Matching", "fuzzy-matching"), ("Record Matching", "record-matching")],
        "related_resources": [("Duplicate Detection Service", "/cleaning/duplicate-detection/"), ("Duplicate Detection Validation", "/validation/duplicate-detection/"), ("Salesforce Duplicate Contacts", "/resources/salesforce-duplicate-contacts.html")],
        "cta_headline": "How many duplicates are hiding in your CRM?",
        "cta_text": "We'll scan your database, find the duplicates, and merge them into clean, consolidated records.",
    },
    {
        "slug": "email-deliverability",
        "term": "Email Deliverability",
        "meta_desc": "Email deliverability measures whether your emails reach the inbox or land in spam. Learn what factors affect deliverability and how data quality plays a central role.",
        "definition": '<p><strong>Email deliverability</strong> is the measure of whether your emails successfully reach the recipient\'s inbox rather than bouncing, being rejected, or landing in spam. It\'s determined by a combination of sender reputation, email authentication, content quality, and list hygiene. A 95% deliverability rate means 5 out of every 100 emails you send never reach anyone.</p>',
        "why_matters": "<p>You can write the best email in the world, but it doesn't matter if it never arrives. Poor deliverability is often invisible: your email platform shows \"sent\" but 20% of those messages hit spam or get silently rejected. Your open rates look low, your reply rates look terrible, and you blame the copy when the real problem is that half your list is outdated. ISPs penalize senders who consistently hit bad addresses, and recovery takes weeks.</p>",
        "how_heading": "Factors That Affect Deliverability",
        "how_items": [
            ("List quality", "Bounce rate is the #1 factor. Sending to invalid addresses tells ISPs you don't maintain your list"),
            ("Sender reputation", "ISPs assign a score to your sending domain and IP. High bounces, spam complaints, and low engagement lower it"),
            ("Email authentication", "SPF, DKIM, and DMARC records prove your emails are legitimate. Without them, you look like a spammer"),
            ("Engagement rates", "ISPs track opens, clicks, and replies. Low engagement signals that recipients don't want your emails"),
            ("Spam traps", "Old, abandoned email addresses that ISPs monitor. Sending to them proves you're not cleaning your list"),
        ],
        "example": "<p>A company's cold email reply rate drops from 4% to 0.5% over three months. Investigation reveals their sender reputation score dropped from 85 to 42 because 18% of their list was invalid addresses accumulated over two years. They clean the list, remove 3,400 bad addresses, warm up a new sending domain, and reply rates recover to 3.5% within six weeks.</p>",
        "related_terms": [("Bounce Rate (Email)", "bounce-rate"), ("Sender Reputation", "sender-reputation"), ("Email Validation", "email-validation")],
        "related_resources": [("Email Deliverability & Data Quality", "/resources/email-deliverability-data-quality.html"), ("Email Verification", "/cleaning/email-verification/"), ("Email List Cleaning", "/cleaning/email-list-cleaning/")],
        "cta_headline": "Emails not getting through?",
        "cta_text": "We'll clean your list, remove the addresses hurting your reputation, and get your deliverability back on track.",
    },
    {
        "slug": "entity-resolution",
        "term": "Entity Resolution",
        "meta_desc": "Entity resolution determines whether two records refer to the same real-world person or company. Learn how it works and why it's harder than exact matching.",
        "definition": '<p><strong>Entity resolution</strong> (also called record linkage or identity resolution) is the process of determining whether two or more records in a dataset refer to the same real-world entity, a person, company, or location. It\'s more sophisticated than simple deduplication because it works across datasets with different schemas, formats, and levels of completeness. "Robert J. Smith, VP Sales, Acme" in your CRM and "Bob Smith, Sales, Acme Corporation" in a trade show list might be the same person. Entity resolution figures that out.</p>',
        "why_matters": "<p>When you're combining data from multiple sources, CRM exports, event lists, purchased data, website sign-ups, the same entities appear in different forms. Without resolution, you can't build a unified view of your customers or prospects. You end up with fragmented profiles where some data lives in one record and some in another, and nobody can see the complete picture.</p>",
        "how_heading": "How Entity Resolution Works",
        "how_items": [
            ("Blocking", "Group records by a shared attribute (same company domain, same last name) to reduce the number of comparisons needed"),
            ("Pairwise comparison", "Compare blocked records across multiple fields: name similarity, email, phone, company, title"),
            ("Probabilistic scoring", "Calculate the likelihood that two records are the same entity based on how many fields match and how closely"),
            ("Clustering", "Group all records that resolve to the same entity, even if they were matched through intermediate records"),
            ("Merge or link", "Either merge records into a single golden record, or create a persistent link between them for cross-referencing"),
        ],
        "example": "<p>A company acquires a competitor and needs to merge their customer databases. The acquiring company's CRM has 40,000 contacts. The acquired company has 25,000. Entity resolution finds 8,000 contacts that exist in both databases, merges them, and produces a unified database of 57,000 unique contacts with the best data from each source.</p>",
        "related_terms": [("Record Matching", "record-matching"), ("Golden Record", "golden-record"), ("Data Deduplication", "data-deduplication")],
        "related_resources": [("Record Matching Service", "/cleaning/record-matching/"), ("Database Merge", "/use-cases/database-merge/"), ("Data Deduplication", "/cleaning/data-deduplication/")],
        "cta_headline": "Merging databases from different sources?",
        "cta_text": "We'll resolve entities across your datasets and build a unified, deduplicated view of every contact and company.",
    },
    {
        "slug": "fill-rate",
        "term": "Fill Rate",
        "meta_desc": "Fill rate measures the percentage of records where a specific field has a value. Learn why fill rate matters and what rates to target for key fields.",
        "definition": '<p><strong>Fill rate</strong> (also called field coverage or completeness rate) is the percentage of records in your database that have a value in a specific field. If 7,500 out of 10,000 contact records have an email address, your email fill rate is 75%. Fill rate is the simplest and most actionable data quality metric because it tells you exactly how much of your data is usable for a given purpose.</p>',
        "why_matters": "<p>Low fill rates directly limit what your team can do. A 50% email fill rate means half your database can't receive email campaigns. A 30% phone fill rate means 70% of contacts can't be called. A 40% industry fill rate means your segmentation excludes most of your records. Every percentage point of fill rate translates to more contacts you can reach, score, route, and convert.</p>",
        "how_heading": "Target Fill Rates by Field",
        "how_items": [
            ("Email address", "Target 90%+. Email is the primary communication channel in B2B. Below 80% means your database has serious gaps"),
            ("Phone number", "Target 70%+. Direct dials are harder to find than emails. 50% is average. Above 70% is strong"),
            ("Job title", "Target 85%+. Needed for routing, scoring, and personalization. Titles change frequently so freshness matters too"),
            ("Company size", "Target 80%+. Essential for segmentation and lead scoring. Usually available from firmographic providers"),
            ("Industry", "Target 85%+. Required for territory assignment, content targeting, and ICP matching"),
        ],
        "example": "<p>A marketing team audits their 45,000-record database. Fill rates: email 82%, phone 38%, title 71%, company size 55%, industry 64%. After batch enrichment, fill rates jump to: email 94%, phone 68%, title 89%, company size 91%, industry 93%. Their lead scoring model, which requires all five fields, now works on 60% of records instead of 15%.</p>",
        "related_terms": [("Data Profiling", "data-profiling"), ("Data Append", "data-append"), ("Batch Enrichment", "batch-enrichment")],
        "related_resources": [("Data Quality Metrics", "/resources/data-quality-metrics.html"), ("Data Enrichment Services", "/services/data-enrichment.html"), ("Contact Enrichment", "/enrichment/contact-enrichment/")],
        "cta_headline": "Low fill rates dragging you down?",
        "cta_text": "We'll measure your current fill rates, fill the gaps, and show you the before-and-after numbers.",
    },
    {
        "slug": "first-party-data",
        "term": "First-Party Data",
        "meta_desc": "First-party data is information you collect directly from your customers and prospects. Learn why it's your most valuable data asset and how to maximize it.",
        "definition": '<p><strong>First-party data</strong> is information your organization collects directly from your customers, prospects, and website visitors through your own channels. Form submissions, purchase history, product usage, email engagement, support interactions, and website behavior are all first-party data. You own it, you control it, and it\'s the most reliable data you have because it comes from direct interactions with your business.</p>',
        "why_matters": "<p>With third-party cookies disappearing and privacy regulations tightening, first-party data is becoming the foundation of B2B marketing. It's data you have explicit permission to use. It reflects actual interactions with your brand, not inferred behavior. And unlike purchased lists that decay immediately, first-party data is fresh by definition. The companies that build strong first-party data strategies will have a permanent advantage in targeting, personalization, and measurement.</p>",
        "how_heading": "Types of First-Party Data",
        "how_items": [
            ("Form submissions", "Contact info, company details, and self-reported attributes from gated content, demo requests, and sign-ups"),
            ("Product usage", "Feature adoption, login frequency, usage patterns, and engagement metrics from your product"),
            ("Website behavior", "Pages visited, content downloaded, time on site, and conversion events from your web properties"),
            ("Email engagement", "Opens, clicks, replies, and unsubscribes from your email campaigns"),
            ("Sales interactions", "Call notes, meeting summaries, deal stages, and closed-won/lost reasons from your CRM"),
        ],
        "example": "<p>A company analyzes their first-party data and discovers that prospects who visit the pricing page twice and read a case study have a 45% close rate, versus 8% for all other leads. They build an automated workflow that fast-tracks these \"double pricing page + case study\" leads to sales, increasing conversion without buying any new data.</p>",
        "related_terms": [("Data Governance", "data-governance"), ("Customer Data Platform (CDP)", "customer-data-platform"), ("Lead Scoring", "lead-scoring")],
        "related_resources": [("First-Party Data Strategy", "/resources/first-party-data-strategy.html"), ("Data Governance Without a Team", "/resources/data-governance-without-team.html"), ("Customer Profiling", "/use-cases/customer-profiling/")],
        "cta_headline": "First-party data has gaps?",
        "cta_text": "We'll enrich your CRM records with third-party data to fill the fields your forms didn't capture.",
    },
    {
        "slug": "fuzzy-matching",
        "term": "Fuzzy Matching",
        "meta_desc": "Fuzzy matching finds records that are similar but not identical. Learn the algorithms behind it and why exact matching misses most duplicates.",
        "definition": '<p><strong>Fuzzy matching</strong> identifies records that are similar but not exactly the same. While exact matching only catches identical values ("John Smith" = "John Smith"), fuzzy matching catches variations: "John Smith" matches "Jon Smith," "J. Smith," "Jonathan Smith," and "John P. Smith." It uses algorithms that measure how similar two strings are and returns a confidence score for each potential match.</p>',
        "why_matters": "<p>Exact matching catches less than half of real duplicates. People abbreviate names, misspell companies, use different email formats, and enter phone numbers in different formats. If you only match on exact values, \"Acme Corporation\" and \"Acme Corp\" look like two different companies. Fuzzy matching closes this gap and catches the near-duplicates that exact matching misses entirely.</p>",
        "how_heading": "Common Fuzzy Matching Algorithms",
        "how_items": [
            ("Levenshtein distance", "Counts the minimum number of single-character edits needed to turn one string into another. 'Smith' to 'Smyth' = distance of 1"),
            ("Jaro-Winkler", "Measures character-level similarity with extra weight on matching prefixes. Good for names where the beginning is most reliable"),
            ("Soundex/Metaphone", "Encodes names by how they sound, not how they're spelled. Catches 'Smith' and 'Smythe' as phonetic matches"),
            ("Token-based matching", "Compares sets of words regardless of order. 'Acme Inc' and 'Inc Acme' get a high score because the same words are present"),
            ("Composite scoring", "Combine multiple algorithms and multiple fields for an overall match confidence score"),
        ],
        "example": '<p>A database has "Robert Johnson, Acme Corp" and "Bob Johnson, Acme Corporation" with different email addresses. Exact matching finds nothing. Fuzzy matching detects: name similarity 78% (Robert/Bob are known nicknames), company similarity 92% (Corp/Corporation), same area code on phone numbers. Composite score: 87% match probability. Flagged for review.</p>',
        "related_terms": [("Duplicate Detection", "duplicate-detection"), ("Entity Resolution", "entity-resolution"), ("Record Matching", "record-matching")],
        "related_resources": [("Record Matching Service", "/cleaning/record-matching/"), ("Duplicate Detection", "/cleaning/duplicate-detection/"), ("Data Deduplication", "/cleaning/data-deduplication/")],
        "cta_headline": "Duplicates slipping through exact matching?",
        "cta_text": "We use fuzzy matching across name, company, email, and phone to catch the near-duplicates your CRM misses.",
    },
    {
        "slug": "golden-record",
        "term": "Golden Record",
        "meta_desc": "A golden record is the single, authoritative version of a person or company in your database. Learn how golden records are created from merged duplicate data.",
        "definition": '<p>A <strong>golden record</strong> is the single, most complete and accurate version of an entity (person, company, or account) in your database after duplicate records have been identified and merged. When three records for the same person each have different partial data, the golden record combines the best information from all three: the most recent email, the most complete address, the most accurate title, and the most current phone number.</p>',
        "why_matters": "<p>Without golden records, your team works with conflicting information. Sales looks at one record and sees \"VP of Marketing.\" Marketing looks at another record for the same person and sees \"Director of Growth.\" Support looks at a third and sees no title at all. Golden records eliminate this conflict by establishing one authoritative version that all teams reference. It's the foundation of a \"single source of truth\" for your customer data.</p>",
        "how_heading": "How Golden Records Are Created",
        "how_items": [
            ("Duplicate identification", "Find all records that represent the same entity using fuzzy matching, cross-field comparison, and confidence scoring"),
            ("Survivorship rules", "Define which value wins when duplicates conflict. Common rules: most recent, most complete, most reliable source"),
            ("Field-level merging", "Pick the best value for each field independently. Record A might have the best email while Record B has the best phone"),
            ("Audit trail", "Preserve the original records or a log of what was merged so you can reverse decisions if needed"),
            ("Ongoing maintenance", "Set rules to prevent new duplicates and automatically route potential matches for review"),
        ],
        "example": "<p>Three CRM records for the same person: Record A (email verified last month, title is outdated), Record B (current title from LinkedIn, email bounces), Record C (has direct phone number, everything else is old). The golden record takes the email from A, title from B, phone from C, and marks the merged record with the most recent modification date.</p>",
        "related_terms": [("Entity Resolution", "entity-resolution"), ("Data Deduplication", "data-deduplication"), ("Master Data Management", "master-data-management")],
        "related_resources": [("Data Deduplication Service", "/cleaning/data-deduplication/"), ("Database Merge", "/use-cases/database-merge/"), ("Master Data Management", "/use-cases/master-data-management/")],
        "cta_headline": "Conflicting records for the same contact?",
        "cta_text": "We'll merge your duplicates into golden records where every field has the best available data.",
    },
    {
        "slug": "industry-classification",
        "term": "Industry Classification",
        "meta_desc": "Industry classification assigns standardized codes like NAICS or SIC to businesses. Learn why classification matters for segmentation, routing, and compliance.",
        "definition": '<p><strong>Industry classification</strong> assigns a standardized code to a business based on its primary economic activity. The two main systems are NAICS (North American Industry Classification System) and SIC (Standard Industrial Classification). NAICS code 541511 means \"Custom Computer Programming Services.\" SIC code 7372 means \"Prepackaged Software.\" These codes create a universal language for categorizing businesses so they can be compared, filtered, and analyzed consistently.</p>',
        "why_matters": "<p>Free-text industry fields in CRMs are chaos. \"Software,\" \"SaaS,\" \"Technology,\" \"Tech,\" \"IT Services,\" and \"Information Technology\" might all describe the same company. You can't segment, route, or report on inconsistent categories. Standardized industry codes fix this. They also enable compliance with regulations that restrict marketing to certain industries and make your data compatible with external datasets that use the same classification system.</p>",
        "how_heading": "How Industry Classification Works",
        "how_items": [
            ("NAICS codes", "6-digit codes organized hierarchically. First 2 digits = sector, next 2 = subsector, next = industry group, last = specific industry"),
            ("SIC codes", "4-digit codes still used by SEC filings and some government databases. Older but still relevant for financial data"),
            ("Automated classification", "Match company descriptions, website content, and business registration data against code definitions"),
            ("Manual review", "For ambiguous cases where a company spans multiple industries, human judgment picks the primary classification"),
            ("Enrichment", "Append NAICS/SIC codes to existing records that only have free-text industry descriptions"),
        ],
        "example": "<p>A sales team wants to target healthcare IT companies. Their CRM has \"Healthcare,\" \"Health,\" \"Medical,\" \"HealthTech,\" and \"Health IT\" scattered across 3,000 records. After classification, each record gets a 6-digit NAICS code. Filtering by NAICS 5112 (Software Publishers) + healthcare-related keywords produces a precise list of 340 companies.</p>",
        "related_terms": [("Firmographic Data", "firmographic-data"), ("Data Standardization", "data-standardization"), ("Customer Segmentation", "customer-segmentation")],
        "related_resources": [("NAICS Code Enrichment", "/enrichment/naics-code-enrichment/"), ("SIC Code Enrichment", "/enrichment/sic-code-enrichment/"), ("Industry Classification Enrichment", "/enrichment/industry-classification-enrichment/")],
        "cta_headline": "Industry data a mess?",
        "cta_text": "We'll classify every company in your database with standardized NAICS and SIC codes.",
    },
    {
        "slug": "job-title-normalization",
        "term": "Job Title Normalization",
        "meta_desc": "Job title normalization standardizes the thousands of title variations in your CRM into consistent categories. Learn why it matters for routing, scoring, and segmentation.",
        "definition": '<p><strong>Job title normalization</strong> standardizes the wide variety of job titles in your database into a consistent taxonomy of roles and seniority levels. \"VP Sales,\" \"Vice President of Sales,\" \"VP, Sales & Business Development,\" and \"Head of Sales\" all map to a normalized title and a seniority level (in this case, VP-level). Normalization creates structure from the chaos of free-text title fields.</p>',
        "why_matters": "<p>A typical B2B database has thousands of unique job title values. This makes segmentation, lead scoring, and routing almost impossible. Is \"Growth Lead\" a manager or a director? Is \"Chief Revenue Officer\" the same seniority as \"SVP Revenue\"? Without normalization, your lead routing sends VPs to the SMB team and your lead scoring treats a C-suite exec the same as an individual contributor.</p>",
        "how_heading": "What Normalization Adds",
        "how_items": [
            ("Standardized title", "Map variations to a canonical form. 'VP Sales,' 'Vice President, Sales,' and 'VP of Sales' all become 'Vice President of Sales'"),
            ("Seniority level", "Assign a level: C-Suite, VP, Director, Manager, Senior, Individual Contributor, Intern"),
            ("Department", "Extract the department: Sales, Marketing, Engineering, Finance, Operations, HR, IT"),
            ("Decision-maker flag", "Identify whether the title indicates someone who can approve a purchase in your product category"),
            ("Persona mapping", "Map titles to your buyer personas so marketing automation can target the right content to the right people"),
        ],
        "example": '<p>A company\'s CRM has 8,200 unique title values across 45,000 contacts. After normalization, those collapse to 420 standardized titles with seniority levels. Lead scoring improves because C-suite and VP contacts get proper weighting. Routing works because "Director" and above go to the mid-market team while "Manager" and below go to SMB.</p>',
        "related_terms": [("Data Standardization", "data-standardization"), ("Data Normalization", "data-normalization"), ("Lead Scoring", "lead-scoring")],
        "related_resources": [("Job Title Normalization Service", "/cleaning/job-title-normalization/"), ("Job Title Enrichment", "/enrichment/job-title-enrichment/"), ("Salesforce Job Title Standardization", "/resources/salesforce-job-title-standardization.html")],
        "cta_headline": "Thousands of title variations?",
        "cta_text": "We'll normalize every title in your database to a standardized role, seniority level, and department.",
    },
    {
        "slug": "lead-qualification",
        "term": "Lead Qualification",
        "meta_desc": "Lead qualification determines whether a prospect is worth pursuing. Learn qualification frameworks and how enriched data makes the process faster and more accurate.",
        "definition": '<p><strong>Lead qualification</strong> is the process of evaluating whether a prospect has the budget, authority, need, and timeline to become a customer. It separates leads worth pursuing from those that will waste your sales team\'s time. Qualification can happen through data (firmographic fit, behavioral signals) or conversation (discovery calls, BANT questions), but the best teams use both.</p>',
        "why_matters": "<p>Sales reps have finite hours. If they spend time on leads that will never close, they miss the ones that would. Without qualification, reps either cherry-pick based on gut feeling or try to work everything equally. Both approaches leave money on the table. Data-driven qualification lets you prioritize the leads most likely to convert before a rep ever picks up the phone, which means more pipeline per rep hour.</p>",
        "how_heading": "Common Qualification Frameworks",
        "how_items": [
            ("BANT", "Budget, Authority, Need, Timeline. The classic framework: can they pay, can they decide, do they have the problem, when do they need a solution?"),
            ("MEDDIC", "Metrics, Economic Buyer, Decision Criteria, Decision Process, Identify Pain, Champion. Deeper qualification for enterprise sales"),
            ("ICP fit scoring", "Score leads against your ideal customer profile using firmographic data: company size, industry, tech stack, growth stage"),
            ("Behavioral scoring", "Track engagement signals: website visits, content downloads, email opens, and demo requests as indicators of intent"),
            ("Negative qualification", "Identify disqualifying criteria early: too small, wrong industry, no budget cycle, competitor lock-in. Stop pursuing fast"),
        ],
        "example": "<p>An SDR team gets 200 inbound leads per week. Before enrichment, they manually research each one to determine fit, taking 10 minutes per lead. After enrichment, each lead arrives with company size, industry, tech stack, and seniority level already filled in. Automated scoring disqualifies 80 immediately and ranks the remaining 120 by fit. Rep productivity doubles because they start with the best leads instead of researching all 200.</p>",
        "related_terms": [("Lead Scoring", "lead-scoring"), ("Ideal Customer Profile (ICP)", "ideal-customer-profile"), ("MQL (Marketing Qualified Lead)", "mql")],
        "related_resources": [("Lead Qualification Use Case", "/use-cases/lead-qualification/"), ("ICP Development", "/use-cases/icp-development/"), ("Lead Scoring", "/use-cases/lead-scoring/")],
        "cta_headline": "Reps wasting time on bad leads?",
        "cta_text": "We'll enrich your inbound leads with the data needed for instant qualification so your team only works the winners.",
    },
    {
        "slug": "lead-routing",
        "term": "Lead Routing",
        "meta_desc": "Lead routing automatically assigns leads to the right sales rep based on territory, company size, or other criteria. Learn why data quality determines routing accuracy.",
        "definition": '<p><strong>Lead routing</strong> is the automated process of assigning incoming leads to the correct sales representative based on predefined rules: territory, company size, industry, account ownership, or round-robin distribution. Good routing gets the right lead to the right rep in minutes. Bad routing sends enterprise accounts to the SMB team, West Coast leads to East Coast reps, and existing customer inquiries to new business SDRs.</p>',
        "why_matters": "<p>Speed-to-lead is one of the strongest predictors of conversion. Responding within 5 minutes versus 30 minutes increases contact rates by 100x (per InsideSales research). But speed means nothing if the lead goes to the wrong person. A misrouted lead sits in the wrong rep's queue, gets ignored or deprioritized, and by the time it reaches the right person, the prospect has moved on. Accurate data is the prerequisite for accurate routing.</p>",
        "how_heading": "Common Routing Criteria",
        "how_items": [
            ("Territory", "Route by geography (state, region, country). Requires accurate, standardized address or location data"),
            ("Company size", "SMB leads go to one team, mid-market to another, enterprise to another. Requires employee count or revenue data"),
            ("Industry", "Specialized reps handle healthcare, financial services, or technology verticals. Requires standardized industry classification"),
            ("Account ownership", "If the lead's company already exists in CRM, route to the account owner. Requires company name matching"),
            ("Round-robin", "Distribute evenly among reps when no specific criteria apply. Fair, but misses specialization benefits"),
        ],
        "example": "<p>A company routes leads by company size: under 100 employees to SMB, 100-1000 to mid-market, 1000+ to enterprise. But 35% of inbound leads have no company size data. Those leads go to a \"general\" queue where response time averages 8 hours instead of 12 minutes. After enriching inbound leads in real-time with company size, the general queue drops to 5% and average response time falls to 15 minutes.</p>",
        "related_terms": [("Lead Scoring", "lead-scoring"), ("Territory Planning", "territory-planning"), ("Lead Qualification", "lead-qualification")],
        "related_resources": [("Lead Routing & Broken Data", "/resources/lead-routing-broken-data.html"), ("Lead Routing Use Case", "/use-cases/lead-routing/"), ("Data Enrichment Services", "/services/data-enrichment.html")],
        "cta_headline": "Leads going to the wrong reps?",
        "cta_text": "We'll enrich your leads with company size, industry, and location data so routing rules actually work.",
    },
    {
        "slug": "lead-scoring",
        "term": "Lead Scoring",
        "meta_desc": "Lead scoring assigns a numerical value to each lead based on how likely they are to convert. Learn how scoring works and why enriched data makes scores more accurate.",
        "definition": '<p><strong>Lead scoring</strong> assigns a numerical value to each lead based on how well they match your ideal customer profile (fit score) and how engaged they are with your brand (behavior score). A VP of Sales at a 200-person SaaS company who visited your pricing page three times scores higher than an intern at a 5-person startup who downloaded one whitepaper. Scoring lets sales teams prioritize their outreach based on data instead of intuition.</p>',
        "why_matters": "<p>Without scoring, every lead looks the same in the queue. Reps either work them first-in-first-out (which ignores quality) or cherry-pick based on company name recognition (which misses hidden gems). Lead scoring solves this by ranking leads objectively. But here's the catch: scoring is only as good as the data feeding it. If company size, industry, and title fields are missing or wrong, the score is meaningless. Most broken lead scoring models have a data quality problem, not a model problem.</p>",
        "how_heading": "How Lead Scoring Works",
        "how_items": [
            ("Fit scoring", "Award points based on firmographic match: company size, industry, tech stack, geography, growth stage"),
            ("Behavior scoring", "Award points for engagement: pricing page visits, demo requests, email clicks, webinar attendance"),
            ("Negative scoring", "Deduct points for disqualifying signals: competitor employee, student email domain, unsubscribed from emails"),
            ("Score thresholds", "Define what score triggers action: 80+ = fast-track to sales, 50-79 = nurture, below 50 = low priority"),
            ("Model refinement", "Compare scores against actual conversion data quarterly. Adjust weights for the attributes that actually predict deals"),
        ],
        "example": "<p>A company builds a scoring model: 20 points for 100-500 employees, 15 for SaaS industry, 10 for VP+ title, 25 for demo request, 10 for pricing page visit. A lead scores 80 and gets called within an hour. Another lead with the same behavior but at a 5-person company scores 45 and goes into the nurture track. Close rates for 80+ leads are 4x higher than unsorted leads.</p>",
        "related_terms": [("Lead Qualification", "lead-qualification"), ("Ideal Customer Profile (ICP)", "ideal-customer-profile"), ("MQL (Marketing Qualified Lead)", "mql")],
        "related_resources": [("Lead Scoring With Enriched Data", "/resources/lead-scoring-with-enriched-data.html"), ("Why Lead Scoring Isn't Working", "/resources/lead-scoring-not-working.html"), ("Lead Scoring Model", "/analysis/lead-scoring-model/")],
        "cta_headline": "Lead scoring not working?",
        "cta_text": "The problem is usually missing data, not bad models. We'll enrich your leads so your scoring has the inputs it needs.",
    },
]

if __name__ == "__main__":
    created = 0
    for t in TERMS:
        slug_dir = os.path.join(GLOSSARY_DIR, t["slug"])
        os.makedirs(slug_dir, exist_ok=True)
        html = generate_page(
            t["slug"], t["term"], t["meta_desc"], t["definition"],
            t["why_matters"], t["how_heading"], t["how_items"], t["example"],
            t["related_terms"], t["related_resources"], t["cta_headline"], t["cta_text"]
        )
        with open(os.path.join(slug_dir, "index.html"), "w") as f:
            f.write(html)
        created += 1
        print(f"  Created: glossary/{t['slug']}/index.html")
    print(f"\nBatch 2 complete: {created} glossary pages created.")
