#!/usr/bin/env python3
"""Generate glossary term pages - Batch 3 (17 terms)."""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from glossary_batch1 import generate_page

SITE_ROOT = "/Users/rome/Documents/projects/verum-website"
GLOSSARY_DIR = os.path.join(SITE_ROOT, "glossary")

TERMS = [
    {
        "slug": "lookalike-modeling",
        "term": "Lookalike Modeling",
        "meta_desc": "Lookalike modeling finds new prospects that resemble your best existing customers. Learn how it works and what data inputs produce the best results.",
        "definition": '<p><strong>Lookalike modeling</strong> analyzes the attributes of your best customers and finds new prospects that share those same characteristics. You define a seed audience (your top 100 accounts, your fastest-closing deals, your lowest-churn customers), and the model identifies companies in the broader market that look similar based on firmographic, technographic, and behavioral data.</p>',
        "why_matters": "<p>Your best customers share patterns you might not see intuitively. Maybe they're all between 150-400 employees, use Salesforce, and hired a RevOps person in the last year. Lookalike modeling surfaces these patterns and finds thousands of companies that match. Instead of guessing who to target, you're targeting companies that statistically resemble the ones already paying you.</p>",
        "how_heading": "How Lookalike Modeling Works",
        "how_items": [
            ("Seed audience creation", "Define your best customers based on LTV, deal size, retention rate, or other success metrics"),
            ("Feature extraction", "Identify the attributes your seed audience shares: company size, industry, tech stack, growth rate, funding stage"),
            ("Pattern detection", "Statistical models find which combinations of attributes are most predictive of customer success"),
            ("Prospect scoring", "Score every company in the addressable market on how closely they resemble the seed audience"),
            ("List delivery", "Deliver a ranked list of lookalike prospects with enriched contact data ready for outreach"),
        ],
        "example": "<p>A company's 50 best customers are all B2B SaaS, 100-500 employees, using HubSpot, and growing headcount by 20%+ year-over-year. The lookalike model scans 200,000 companies and finds 3,200 that match all four criteria. The sales team starts prospecting into a list where every account already looks like a great customer.</p>",
        "related_terms": [("Ideal Customer Profile (ICP)", "ideal-customer-profile"), ("Customer Segmentation", "customer-segmentation"), ("Firmographic Data", "firmographic-data")],
        "related_resources": [("Lookalike Modeling Use Case", "/use-cases/lookalike-modeling/"), ("ICP Analysis Service", "/services/icp-analysis.html"), ("ICP Development", "/use-cases/icp-development/")],
        "cta_headline": "Want more prospects like your best customers?",
        "cta_text": "We'll analyze your top accounts, find the patterns, and build a lookalike list ready for outreach.",
    },
    {
        "slug": "market-sizing",
        "term": "Market Sizing (TAM/SAM/SOM)",
        "meta_desc": "Market sizing calculates TAM, SAM, and SOM to quantify your market opportunity. Learn what each metric means and how data makes the estimates reliable.",
        "definition": '<p><strong>Market sizing</strong> quantifies the revenue opportunity for your product or service. It uses three nested metrics: TAM (Total Addressable Market) is everyone who could theoretically buy. SAM (Serviceable Addressable Market) is the subset you can actually reach with your current model. SOM (Serviceable Obtainable Market) is the realistic share you can capture in the near term.</p>',
        "why_matters": "<p>Investors, boards, and executives want to know the size of the opportunity. \"It's a big market\" isn't an answer. You need numbers. But top-down estimates from analyst reports are notoriously unreliable because they define markets differently than your product does. Bottom-up market sizing, counting actual companies that match your ICP and multiplying by your average deal size, produces numbers you can defend and actually use for planning.</p>",
        "how_heading": "How to Size a Market",
        "how_items": [
            ("Define your ICP", "Specify the company attributes that define a good customer: industry, size, geography, tech stack, buying signals"),
            ("Count the companies", "Use firmographic databases to count how many companies match your ICP criteria"),
            ("Estimate penetration", "How many of those companies would realistically buy? Apply conversion rates from your sales data"),
            ("Calculate revenue", "Multiply addressable companies by your average contract value to get TAM, SAM, and SOM"),
            ("Validate against reality", "Compare your bottom-up estimate against industry reports, competitor revenue, and your own growth rate"),
        ],
        "example": "<p>A data enrichment company defines their ICP: B2B companies with 50-1000 employees, using Salesforce or HubSpot, in the US. Database search finds 84,000 matching companies (TAM). They can reach 35,000 through their current sales channels (SAM). At a 2% close rate and $5,000 average deal, the SOM is $3.5M. This number is credible because every input is measurable.</p>",
        "related_terms": [("Ideal Customer Profile (ICP)", "ideal-customer-profile"), ("Customer Segmentation", "customer-segmentation"), ("Firmographic Data", "firmographic-data")],
        "related_resources": [("Market Sizing Use Case", "/use-cases/market-sizing/"), ("TAM SAM SOM Analysis", "/use-cases/tam-sam-som-analysis/"), ("Market Analysis", "/analysis/market-analysis/")],
        "cta_headline": "Need a defensible market size?",
        "cta_text": "We'll count the companies that match your ICP and calculate TAM, SAM, and SOM with real data.",
    },
    {
        "slug": "master-data-management",
        "term": "Master Data Management",
        "meta_desc": "Master data management creates a single authoritative source for critical business data across all systems. Learn what MDM includes and when you need it.",
        "definition": '<p><strong>Master data management (MDM)</strong> is the discipline of creating and maintaining a single, authoritative source of truth for critical business entities: customers, companies, products, employees, and locations. MDM ensures that every system across your organization references the same definitions, the same records, and the same data. When your CRM, marketing automation, billing system, and support tool all agree on who a customer is, that\'s MDM working.</p>',
        "why_matters": "<p>As companies grow and add tools, the same data gets scattered across 10-20 systems, each with its own version of the truth. Customer \"Acme Corp\" has different addresses in Salesforce, different contact counts in HubSpot, and different revenue in the billing system. MDM reconciles these differences so every team works from the same accurate record.</p>",
        "how_heading": "Core Components of MDM",
        "how_items": [
            ("Data model", "Define the canonical structure for each entity: what fields exist, what formats are allowed, what values are valid"),
            ("Matching and merging", "Identify duplicates across systems and create golden records with the best data from each source"),
            ("Governance rules", "Establish who can create, update, or delete master records, and what approval workflows are required"),
            ("Synchronization", "Push master data to all connected systems so changes propagate everywhere automatically"),
            ("Quality monitoring", "Continuously measure accuracy, completeness, and consistency against defined thresholds"),
        ],
        "example": "<p>A 500-person company has customer data in Salesforce, HubSpot, Zendesk, Stripe, and Snowflake. The same customer has slightly different records in each. MDM establishes Salesforce as the master for account data, reconciles discrepancies, and sets up sync rules so that when an account is updated in Salesforce, it flows to all other systems within minutes.</p>",
        "related_terms": [("Golden Record", "golden-record"), ("Data Governance", "data-governance"), ("Data Integration", "data-integration")],
        "related_resources": [("Master Data Management Use Case", "/use-cases/master-data-management/"), ("Data Integration", "/use-cases/data-integration/"), ("Database Merge", "/use-cases/database-merge/")],
        "cta_headline": "Data living in too many places?",
        "cta_text": "We'll help you build a single source of truth by cleaning, merging, and standardizing your customer data.",
    },
    {
        "slug": "match-rate",
        "term": "Match Rate",
        "meta_desc": "Match rate measures what percentage of your records a data provider can find and enrich. Learn what affects match rates and what numbers to expect.",
        "definition": '<p><strong>Match rate</strong> is the percentage of records you submit for enrichment that a data provider can successfully match against their database and return results for. If you send 10,000 contacts and the provider finds and enriches 7,500, the match rate is 75%. Match rate is the single most important metric for evaluating an enrichment provider because it directly determines how many records you\'ll actually get data back on.</p>',
        "why_matters": "<p>A provider with amazing data quality but a 30% match rate leaves 70% of your database untouched. High match rates matter because the records you most want enriched, the ones missing data, are often the hardest to match. Using multiple providers in a waterfall approach (trying the next source when the first one doesn't match) can push overall match rates from 60% with a single provider to 85%+ with three.</p>",
        "how_heading": "What Affects Match Rate",
        "how_items": [
            ("Input data quality", "Records with full names and company domains match better than records with just an email or just a name"),
            ("Provider coverage", "Each provider has different strengths. Some cover SMB better, others enterprise. Some are strong in US, others internationally"),
            ("Record freshness", "People who changed jobs recently may not appear in the provider's database yet. Newer data matches worse"),
            ("Industry coverage", "Some providers have deep coverage in tech/SaaS but thin coverage in healthcare, manufacturing, or government"),
            ("Waterfall strategy", "Using multiple providers sequentially improves overall match rates by catching records that any single provider misses"),
        ],
        "example": "<p>A company sends 20,000 contacts to Provider A. Match rate: 65%. They send the 7,000 unmatched records to Provider B. Match rate on the remainder: 45%. They send the remaining 3,850 to Provider C. Match rate: 30%. Combined match rate across all three: 87%. Single-provider would have been 65%. The waterfall approach found 4,400 additional matches.</p>",
        "related_terms": [("Fill Rate", "fill-rate"), ("Contact Data Waterfall", "contact-waterfall"), ("Data Append", "data-append")],
        "related_resources": [("Contact Data Waterfall Guide", "/resources/contact-data-waterfall.html"), ("Data Enrichment Services", "/services/data-enrichment.html"), ("B2B Data Enrichment", "/enrichment/b2b-data-enrichment/")],
        "cta_headline": "Low match rates from your current provider?",
        "cta_text": "We use 50+ sources in a waterfall approach to maximize match rates. Send us a sample and we'll show you the difference.",
    },
    {
        "slug": "mql",
        "term": "MQL (Marketing Qualified Lead)",
        "meta_desc": "An MQL is a lead that marketing has qualified based on engagement and fit criteria. Learn how MQLs are defined and why the sales-marketing handoff often breaks.",
        "definition": '<p>An <strong>MQL (Marketing Qualified Lead)</strong> is a lead that has met predefined criteria indicating they\'re worth sales attention. Typically, MQL criteria combine demographic fit (right company size, right industry, right title) with behavioral engagement (downloaded content, attended a webinar, visited the pricing page). When a lead crosses the MQL threshold, marketing \"hands it off\" to sales for follow-up.</p>',
        "why_matters": "<p>The MQL is where marketing and sales alignment either works or breaks. If the MQL definition is too loose, sales gets flooded with low-quality leads and stops trusting marketing. If it's too strict, good leads sit in nurture while competitors reach them first. The definition needs to be agreed upon by both teams and backed by data showing which criteria actually predict conversion. And the data feeding those criteria needs to be accurate, otherwise the threshold is meaningless.</p>",
        "how_heading": "Typical MQL Criteria",
        "how_items": [
            ("Demographic fit", "Company size, industry, job title, and geography match your ICP. This requires enriched data, not just what the form captured"),
            ("Engagement score", "Points accumulated from content downloads, email clicks, page visits, and event attendance exceed a threshold"),
            ("Recency", "Engagement happened recently. A lead who was active 6 months ago but went silent shouldn't be an MQL today"),
            ("Negative disqualification", "Exclude competitors, students, job seekers, and existing customers from MQL status regardless of engagement"),
            ("Intent signals", "Third-party intent data showing the account is actively researching your category adds urgency to the MQL"),
        ],
        "example": "<p>Marketing defines MQL as: 50+ employees, in a target industry, Manager+ title, with 3+ engagements in the last 30 days. Before enrichment, 40% of leads can't be scored because they're missing company size or title. After enrichment, coverage jumps to 92%. Monthly MQL volume increases by 35% because leads that were stuck in \"unknown\" now have enough data to qualify.</p>",
        "related_terms": [("Lead Scoring", "lead-scoring"), ("Lead Qualification", "lead-qualification"), ("Demand Generation", "demand-generation")],
        "related_resources": [("Lead Scoring With Enriched Data", "/resources/lead-scoring-with-enriched-data.html"), ("Lead Qualification", "/use-cases/lead-qualification/"), ("Lead Scoring", "/use-cases/lead-scoring/")],
        "cta_headline": "MQL quality a problem?",
        "cta_text": "We'll enrich your lead data so scoring and qualification actually work, and sales gets leads they want to call.",
    },
    {
        "slug": "net-new-contact",
        "term": "Net-New Contact",
        "meta_desc": "A net-new contact is a person not already in your database. Learn how to find them, verify them, and avoid paying for contacts you already have.",
        "definition": '<p>A <strong>net-new contact</strong> is a person who does not currently exist in your CRM or marketing database. When you buy a list or run a prospecting campaign, net-new contacts are the ones you\'re actually paying for: new leads, new decision-makers, new stakeholders at target accounts. The opposite of net-new is a "match," a contact you already have.</p>',
        "why_matters": "<p>If you're paying for lead lists or prospecting tools, you want to know what percentage of the results are actually new to you versus contacts you already have. A vendor who delivers 10,000 contacts sounds impressive until you discover 6,000 are already in your CRM. That's a 40% net-new rate, and you overpaid significantly. Smart teams deduplicate purchased lists against their existing database before importing to count true net-new additions.</p>",
        "how_heading": "How to Maximize Net-New Contacts",
        "how_items": [
            ("Suppress existing records", "Before any prospecting, export your current database and provide it to the vendor as a suppression list"),
            ("Target whitespace", "Identify accounts in your ICP where you have zero contacts. These are guaranteed net-new opportunities"),
            ("Expand buying committees", "For accounts where you have one contact, find additional stakeholders. New people at known companies are still net-new"),
            ("Verify before importing", "Run email verification and title checks on net-new contacts before adding them to your CRM"),
            ("Track net-new rate", "Measure what percentage of every list purchase or campaign is truly new. Hold vendors accountable"),
        ],
        "example": "<p>A sales team buys a list of 5,000 contacts targeting healthcare companies. They match it against their 40,000-record CRM and find 1,800 already exist. The true net-new count is 3,200. After verification, 2,900 have valid emails. Those 2,900 verified net-new contacts are what the team actually gained from the purchase.</p>",
        "related_terms": [("Data Deduplication", "data-deduplication"), ("Data Append", "data-append"), ("Prospect List Building", "prospect-list-building")],
        "related_resources": [("Net-New Contact Discovery", "/discovery/net-new-contact-discovery/"), ("Prospect List Building", "/discovery/prospect-list-building/"), ("Sales Prospecting", "/use-cases/sales-prospecting/")],
        "cta_headline": "Need new contacts at target accounts?",
        "cta_text": "We'll find verified net-new contacts you don't already have and deliver them ready to import.",
    },
    {
        "slug": "pipeline-management",
        "term": "Pipeline Management",
        "meta_desc": "Pipeline management tracks deals through your sales process and forecasts revenue. Learn how data quality impacts pipeline accuracy and what clean data enables.",
        "definition": '<p><strong>Pipeline management</strong> is the practice of tracking, analyzing, and optimizing the deals moving through your sales process. It covers everything from how leads enter the pipeline (MQLs, outbound, referrals) to how deals progress through stages (qualified, demo, proposal, negotiation) to how accurately you can forecast which deals will close and when. Pipeline management turns your CRM from a contact rolodex into a revenue prediction engine.</p>',
        "why_matters": "<p>Your pipeline is only as accurate as the data in it. If contact information is wrong, reps can't reach decision-makers. If company firmographics are missing, deals are in the wrong segment. If duplicate contacts create duplicate opportunities, your forecast is inflated. A VP of Sales who reports $5M in pipeline when the real number is $3.5M (after removing duplicates and dead contacts) is making bad hiring, spending, and forecasting decisions.</p>",
        "how_heading": "How Data Quality Affects Pipeline",
        "how_items": [
            ("Stage accuracy", "Deals stuck in early stages because reps can't reach the right contacts need data enrichment, not more follow-ups"),
            ("Forecast reliability", "Duplicate opportunities and stale deals inflate the pipeline. Regular cleaning gives you a number you can trust"),
            ("Velocity tracking", "Measuring how fast deals move requires consistent data on entry date, stage changes, and close date"),
            ("Coverage analysis", "Do you have enough pipeline to hit quota? Requires accurate deal values and realistic close probabilities"),
            ("Win/loss analysis", "Understanding why deals close or die requires enriched data on the companies and contacts involved"),
        ],
        "example": "<p>A sales leader runs a pipeline review and finds $8M in pipeline. Data audit reveals: $1.2M in duplicate opportunities, $900K in deals where the primary contact left the company, and $600K in deals with no activity for 90+ days. Real pipeline: $5.3M. Painful but accurate. They clean the pipeline, enrich the contacts on active deals, and forecast accuracy improves from 55% to 82%.</p>",
        "related_terms": [("Revenue Intelligence", "revenue-intelligence"), ("Lead Scoring", "lead-scoring"), ("CRM Hygiene", "crm-hygiene")],
        "related_resources": [("Pipeline Management Use Case", "/use-cases/pipeline-management/"), ("Revenue Intelligence", "/use-cases/revenue-intelligence/"), ("CRM Data Cleaning", "/cleaning/crm-data-cleaning/")],
        "cta_headline": "Pipeline numbers you can't trust?",
        "cta_text": "We'll clean your CRM, remove duplicates, update stale contacts, and give you a pipeline number that's real.",
    },
    {
        "slug": "prospect-list-building",
        "term": "Prospect List Building",
        "meta_desc": "Prospect list building creates targeted lists of companies and contacts matching your ICP. Learn how to build lists that your sales team will actually use.",
        "definition": '<p><strong>Prospect list building</strong> is the process of creating a targeted list of companies and contacts that match your ideal customer profile for sales outreach. It combines firmographic filtering (industry, size, location), contact identification (finding the right people at each company), and data verification (confirming emails deliver and phone numbers connect). A good prospect list is the starting point for every outbound sales motion.</p>',
        "why_matters": "<p>Sales reps should spend their time selling, not researching. When reps build their own lists by manually searching LinkedIn, company websites, and Google, they spend 30-40% of their day on research instead of outreach. And the lists they build are inconsistent, each rep has different standards for what counts as a good prospect. Centralized, data-driven list building gives every rep a consistent, verified starting point so they can focus on conversations.</p>",
        "how_heading": "How to Build a Quality Prospect List",
        "how_items": [
            ("Define your ICP criteria", "Company size, industry, geography, tech stack, growth signals, and any other attributes that predict a good customer"),
            ("Source company data", "Use firmographic databases to find all companies matching your criteria"),
            ("Identify contacts", "Find the right people at each company: decision-makers, influencers, and budget holders with the titles you target"),
            ("Verify contact data", "Run email verification and phone validation. A list with 30% bad data is worse than a smaller clean list"),
            ("Enrich for personalization", "Append tech stack, funding data, hiring trends, and other fields that enable relevant outreach"),
        ],
        "example": "<p>A company needs to prospect into mid-market healthcare organizations. They define the ICP: 200-2000 employees, healthcare or health-tech industry, US-based, using Salesforce. The list build returns 1,400 companies with 4,200 verified contacts (VP+ in Operations, IT, and Finance). Each contact has email, phone, LinkedIn URL, and company firmographics. Reps start calling the same day.</p>",
        "related_terms": [("Net-New Contact", "net-new-contact"), ("Ideal Customer Profile (ICP)", "ideal-customer-profile"), ("Data Append", "data-append")],
        "related_resources": [("Prospect List Building", "/discovery/prospect-list-building/"), ("Sales Prospecting", "/use-cases/sales-prospecting/"), ("Business Prospecting", "/use-cases/business-prospecting/")],
        "cta_headline": "Need a prospect list that's ready to call?",
        "cta_text": "Tell us who you sell to. We'll build a verified list of companies and contacts matching your ICP.",
    },
    {
        "slug": "record-matching",
        "term": "Record Matching",
        "meta_desc": "Record matching determines whether records from different sources refer to the same entity. Learn matching techniques and how confidence scoring prevents false merges.",
        "definition": '<p><strong>Record matching</strong> compares records from one or more datasets to determine which ones refer to the same real-world entity. It\'s the core engine behind deduplication, data merging, and entity resolution. Matching evaluates multiple fields simultaneously, name, email, phone, company, address, and produces a confidence score for each potential pair. High-confidence matches merge automatically. Low-confidence matches get reviewed by a human.</p>',
        "why_matters": "<p>Matching is deceptively hard. Exact matching catches the easy duplicates but misses 50%+ of real matches that have variations in spelling, formatting, or completeness. Overly aggressive matching merges records that should stay separate (two different John Smiths at different companies). The balance between catching real duplicates and avoiding false merges determines whether your data gets better or worse after the process.</p>",
        "how_heading": "Matching Strategies",
        "how_items": [
            ("Deterministic matching", "Rules-based: if email matches exactly, it's the same person. Simple, high-precision, but low recall"),
            ("Probabilistic matching", "Statistical: combine partial matches across multiple fields to calculate overall match probability"),
            ("Machine learning", "Train models on your historical merge decisions to improve accuracy over time"),
            ("Blocking strategies", "Reduce computation by only comparing records that share a common attribute like company domain or last name"),
            ("Human-in-the-loop", "Route uncertain matches to reviewers. This prevents false merges that damage data quality"),
        ],
        "example": "<p>Two databases being merged: Database A has \"Sarah Johnson, sj@acme.com\" and Database B has \"S. Johnson, sarah.johnson@acme.com.\" Email matching finds no exact match. But fuzzy name matching (Sarah/S. Johnson = 82% similar) plus domain matching (both @acme.com) produces an 89% overall match score. Auto-merge threshold is 90%, so it goes to human review. The reviewer confirms it's the same person.</p>",
        "related_terms": [("Fuzzy Matching", "fuzzy-matching"), ("Entity Resolution", "entity-resolution"), ("Duplicate Detection", "duplicate-detection")],
        "related_resources": [("Record Matching Service", "/cleaning/record-matching/"), ("Data Deduplication", "/cleaning/data-deduplication/"), ("Database Merge", "/use-cases/database-merge/")],
        "cta_headline": "Matching records across systems?",
        "cta_text": "We'll match your records using multi-field probabilistic scoring and human QA to get it right.",
    },
    {
        "slug": "revenue-intelligence",
        "term": "Revenue Intelligence",
        "meta_desc": "Revenue intelligence uses data from across the revenue team to surface insights on pipeline, deals, and forecasts. Learn what it includes and why data quality is the prerequisite.",
        "definition": '<p><strong>Revenue intelligence</strong> uses data from CRM, email, calls, meetings, and product usage to surface actionable insights about your pipeline, deals, and revenue. It goes beyond basic CRM reporting by automatically capturing activity data (emails sent, meetings booked, calls made), analyzing deal health, and flagging risks like deals with no recent activity or single-threaded contacts. The goal: make revenue more predictable.</p>',
        "why_matters": "<p>Revenue leaders make decisions based on what's in the CRM. If deal values are wrong, if contacts are outdated, if activities aren't logged, those decisions are based on fiction. Revenue intelligence automates data capture so the CRM reflects reality, not what reps remember to log. But automation can only capture what exists. If the underlying contact and account data is inaccurate, the intelligence layer produces confident-sounding insights from bad data.</p>",
        "how_heading": "What Revenue Intelligence Surfaces",
        "how_items": [
            ("Deal risk scoring", "Flag deals where the buyer stopped responding, key contacts left, or the close date slipped multiple times"),
            ("Activity tracking", "Automatically log emails, calls, and meetings so pipeline reviews reflect actual engagement, not self-reported activity"),
            ("Forecast accuracy", "Use historical close rates by stage, rep, and segment to predict which deals will actually close"),
            ("Relationship mapping", "Show which contacts at an account are engaged and where buying committee coverage has gaps"),
            ("Pipeline trends", "Track pipeline creation, velocity, and conversion over time to spot problems before they hit the forecast"),
        ],
        "example": "<p>A revenue intelligence platform flags that a $200K deal has no email activity for 3 weeks and the champion's LinkedIn shows they changed jobs. Without this signal, the rep would have kept it in the forecast for another month. With it, the rep re-engages with a new contact and re-qualifies the deal before it dies silently.</p>",
        "related_terms": [("Pipeline Management", "pipeline-management"), ("Lead Scoring", "lead-scoring"), ("CRM Hygiene", "crm-hygiene")],
        "related_resources": [("Revenue Intelligence Use Case", "/use-cases/revenue-intelligence/"), ("Revenue Analysis", "/analysis/revenue-analysis/"), ("Pipeline Management", "/use-cases/pipeline-management/")],
        "cta_headline": "Revenue data you can't trust?",
        "cta_text": "Clean CRM data is the foundation of revenue intelligence. We'll fix the data so your insights are accurate.",
    },
    {
        "slug": "revenue-operations",
        "term": "Revenue Operations (RevOps)",
        "meta_desc": "Revenue operations aligns sales, marketing, and customer success around shared data, processes, and metrics. Learn what RevOps does and why it depends on data quality.",
        "definition": '<p><strong>Revenue operations (RevOps)</strong> is the organizational function that aligns sales, marketing, and customer success teams around shared data, processes, tools, and metrics. Instead of each team running their own tech stack, managing their own data, and measuring their own KPIs, RevOps centralizes these functions to eliminate silos and optimize the entire revenue engine as one system.</p>',
        "why_matters": "<p>When sales, marketing, and success operate independently, data fractures. Marketing's leads don't match sales' contacts. Sales' pipeline doesn't reconcile with finance's revenue. Customer success can't see what was promised during the sale. RevOps solves this by owning the data layer across all three functions. But if the underlying data is dirty, RevOps inherits everyone's data quality problems simultaneously. Clean data is literally the job.</p>",
        "how_heading": "What RevOps Owns",
        "how_items": [
            ("Tech stack management", "Select, implement, and maintain the tools all revenue teams share: CRM, marketing automation, sales engagement, analytics"),
            ("Data quality", "Own the data standards, cleaning processes, enrichment strategy, and governance rules that keep the CRM reliable"),
            ("Process design", "Build and optimize lead routing, scoring, handoff, and reporting workflows that span marketing, sales, and success"),
            ("Reporting and analytics", "Create unified dashboards that show the full revenue funnel, not just one team's slice of it"),
            ("Forecasting", "Build accurate revenue forecasts using pipeline data, historical conversion rates, and activity signals"),
        ],
        "example": "<p>A company hires their first RevOps person. Week one: they discover that marketing and sales define 'customer' differently in their respective tools. Marketing counts 8,000 customers. Sales counts 6,200. Finance counts 5,800. After reconciliation and deduplication, the real number is 5,950. RevOps standardizes the definition across all systems so everyone works from the same number.</p>",
        "related_terms": [("CRM Hygiene", "crm-hygiene"), ("Data Governance", "data-governance"), ("Pipeline Management", "pipeline-management")],
        "related_resources": [("RevOps Solutions", "/for/revenue-ops/"), ("CRM Data Cleaning", "/cleaning/crm-data-cleaning/"), ("Data Quality Roadmap", "/resources/data-quality-roadmap.html")],
        "cta_headline": "RevOps inheriting dirty data?",
        "cta_text": "We'll clean, deduplicate, and enrich your CRM so your RevOps team can build on a solid foundation.",
    },
    {
        "slug": "sales-intelligence",
        "term": "Sales Intelligence",
        "meta_desc": "Sales intelligence provides data and insights that help reps sell more effectively. Learn what's included and how it differs from basic contact data.",
        "definition": '<p><strong>Sales intelligence</strong> is the collection of data, insights, and signals that help sales teams identify, prioritize, and engage prospects more effectively. It goes beyond basic contact data (name, email, phone) to include buying signals, organizational charts, tech stack data, competitive intelligence, and relationship maps. Sales intelligence answers not just \"who should I call?\" but \"why should I call them now and what should I say?\"</p>',
        "why_matters": "<p>Cold outreach without intelligence is spray and pray. Reps send generic messages to hundreds of contacts and hope something sticks. With sales intelligence, outreach is specific: \"I noticed you just switched from Marketo to HubSpot\" or \"Your CTO posted about data quality challenges on LinkedIn last week.\" This specificity increases response rates 3-5x because the prospect can tell you've done your homework. But intelligence requires accurate, current data. Stale insights are worse than no insights.</p>",
        "how_heading": "Types of Sales Intelligence",
        "how_items": [
            ("Trigger events", "Job changes, funding rounds, acquisitions, new product launches, and office moves that create buying windows"),
            ("Organizational data", "Org charts, reporting structures, and buying committee maps that show who influences purchase decisions"),
            ("Competitive intelligence", "Which competitors a prospect uses, recent vendor switches, and contract renewal timelines"),
            ("Engagement history", "What content they've consumed, which emails they've opened, and when they last visited your website"),
            ("Technographic data", "The tools and technologies a company uses, which reveals both fit and competitive displacement opportunities"),
        ],
        "example": "<p>A rep's dashboard shows: target account just raised Series B ($25M), hired a new VP of Sales last month, posted 6 SDR openings, and their current CRM contract expires in Q3. The rep crafts outreach referencing the growth and the upcoming CRM evaluation. They get a reply within 2 hours. Without the intelligence, this would have been email #47 in a generic sequence.</p>",
        "related_terms": [("Buyer Intent Data", "buyer-intent-data"), ("Buying Signals", "buying-signals"), ("Technographic Data", "technographic-data")],
        "related_resources": [("Signal-Based Selling", "/resources/signal-based-selling.html"), ("Data Enrichment Services", "/services/data-enrichment.html"), ("Sales Prospecting", "/use-cases/sales-prospecting/")],
        "cta_headline": "Reps selling blind?",
        "cta_text": "We'll enrich your target accounts with the intelligence your reps need to have relevant conversations.",
    },
    {
        "slug": "sender-reputation",
        "term": "Sender Reputation",
        "meta_desc": "Sender reputation is a score ISPs assign to your email domain and IP address. Learn what affects it, how to check it, and how to recover from damage.",
        "definition": '<p><strong>Sender reputation</strong> is a score that email service providers (Gmail, Outlook, Yahoo) assign to your sending domain and IP address based on your email behavior. It determines whether your emails land in the inbox, spam folder, or get rejected entirely. Think of it as a credit score for your email: it takes time to build, drops quickly when you make mistakes, and recovering from damage requires patience and discipline.</p>',
        "why_matters": "<p>Your sender reputation is invisible but controls everything. A high reputation means 95%+ inbox placement. A low reputation means 40-60% of your emails go to spam, and your team has no idea because the emails still show as \"sent\" in their platform. The most common reputation killers are sending to invalid addresses (high bounce rate), hitting spam traps, and getting spam complaints. All three are data quality problems.</p>",
        "how_heading": "How to Protect Sender Reputation",
        "how_items": [
            ("Verify before sending", "Run email verification on your list before every campaign. One bad send can tank your reputation"),
            ("Monitor bounce rates", "Keep hard bounce rates below 2%. Above 5% triggers ISP penalties"),
            ("Watch complaint rates", "Keep spam complaints below 0.1%. Above 0.3% and you're in trouble"),
            ("Authenticate your domain", "Set up SPF, DKIM, and DMARC records to prove your emails are legitimate"),
            ("Warm up new domains", "Start with small volumes to trusted contacts and gradually increase. Don't blast 50,000 emails from a new domain"),
        ],
        "example": "<p>A company switches email providers and starts sending from a new domain without warming it up. They send 20,000 emails on day one. ISPs flag the sudden volume, bounce rate hits 8% because the list hasn't been cleaned in months, and inbox placement drops to 35%. It takes 6 weeks of careful, low-volume sending to rebuild the reputation.</p>",
        "related_terms": [("Email Deliverability", "email-deliverability"), ("Bounce Rate (Email)", "bounce-rate"), ("Email Validation", "email-validation")],
        "related_resources": [("Email Deliverability & Data Quality", "/resources/email-deliverability-data-quality.html"), ("Email Verification", "/cleaning/email-verification/"), ("Email List Cleaning", "/cleaning/email-list-cleaning/")],
        "cta_headline": "Sender reputation tanking?",
        "cta_text": "The fix starts with your list. We'll remove the bad addresses, spam traps, and risky contacts dragging your reputation down.",
    },
    {
        "slug": "suppression-list",
        "term": "Suppression List",
        "meta_desc": "A suppression list prevents specific contacts from receiving outreach. Learn the types of suppression lists and why they're critical for compliance and deliverability.",
        "definition": '<p>A <strong>suppression list</strong> is a set of email addresses, phone numbers, or contacts that must be excluded from outreach campaigns. Suppression lists include people who unsubscribed, bounced hard, filed spam complaints, requested removal, or are otherwise prohibited from receiving your communications. Some suppression lists are regulatory (CAN-SPAM opt-outs), some are contractual (do-not-contact requests from clients), and some are strategic (competitors, existing customers).</p>',
        "why_matters": "<p>Ignoring suppression lists creates legal risk, reputation damage, and wasted budget. Sending to someone who unsubscribed violates CAN-SPAM (up to $50,000+ per violation). Sending to a hard-bounced address damages sender reputation. Sending sales emails to existing customers creates a terrible experience. Suppression lists are non-negotiable, and they need to be applied consistently across every team and every tool.</p>",
        "how_heading": "Types of Suppression Lists",
        "how_items": [
            ("Opt-out list", "People who unsubscribed from your emails. Legally required to honor under CAN-SPAM and GDPR"),
            ("Hard bounce list", "Email addresses confirmed as permanently undeliverable. Sending to them again hurts your sender reputation"),
            ("Competitor list", "Employees at competitor companies you don't want receiving your emails or seeing your campaigns"),
            ("Customer list", "Existing customers who should receive account management emails, not sales prospecting"),
            ("Do-not-contact list", "People or companies who explicitly asked not to be contacted, often through legal or compliance channels"),
        ],
        "example": "<p>A marketing team runs a cold email campaign to 15,000 contacts. They forgot to apply the suppression list. Result: 200 emails go to people who previously unsubscribed (CAN-SPAM violation risk), 50 go to competitor employees (security risk), and 300 go to existing customers who get confused. After adding suppression list checks to their workflow, these mistakes stop happening.</p>",
        "related_terms": [("Email Deliverability", "email-deliverability"), ("Sender Reputation", "sender-reputation"), ("Data Governance", "data-governance")],
        "related_resources": [("Email List Cleaning", "/cleaning/email-list-cleaning/"), ("Contact List Cleaning", "/cleaning/contact-list-cleaning/"), ("Email Deliverability & Data Quality", "/resources/email-deliverability-data-quality.html")],
        "cta_headline": "Suppression lists not in order?",
        "cta_text": "We'll help you build and maintain suppression lists so your outreach stays compliant and your reputation stays intact.",
    },
    {
        "slug": "tech-stack-data",
        "term": "Tech Stack Data",
        "meta_desc": "Tech stack data reveals the software tools a company uses. Learn how it's collected, what it tells you about a prospect, and how to use it for sales targeting.",
        "definition": '<p><strong>Tech stack data</strong> (also called technographic data) reveals the specific software tools and technologies a company uses: their CRM, marketing automation, analytics platform, customer support tool, e-commerce platform, cloud infrastructure, and more. It\'s collected through website scanning, job posting analysis, integration marketplace data, and other signals. Tech stack data tells you what a company has already bought, which predicts what they might buy next.</p>',
        "why_matters": "<p>Knowing what tools a prospect uses transforms your sales conversation. If they use your competitor, you pitch displacement. If they use a complementary tool, you pitch integration. If they use nothing in your category, you pitch adoption. Tech stack data also predicts budget: a company paying for Salesforce Enterprise can probably afford your product. A company on a free CRM probably can't. Without this data, every conversation starts from zero.</p>",
        "how_heading": "How Tech Stack Data Is Collected",
        "how_items": [
            ("Website scanning", "Detect JavaScript libraries, tracking pixels, meta tags, and CDN signatures on company websites"),
            ("Job posting analysis", "Required skills and tools listed in job postings reveal what technologies the company uses internally"),
            ("DNS and email analysis", "MX records, SPF records, and email headers reveal email platforms and security tools"),
            ("Integration marketplace", "Public app marketplace listings show which integrations a company has activated"),
            ("Self-reported data", "G2, Capterra, and similar review sites where companies list their tech stack"),
        ],
        "example": "<p>A sales team selling a Salesforce integration filters their target market by 'uses Salesforce' and discovers 12,000 companies in their ICP. They further filter by 'does not use a competitor product' and get 4,500 companies. They then filter by 'hired a Salesforce admin in the last 6 months' and get 800 high-intent targets. Each filter narrows to a more relevant, ready-to-buy audience.</p>",
        "related_terms": [("Technographic Data", "technographic-data"), ("Firmographic Data", "firmographic-data"), ("Buyer Intent Data", "buyer-intent-data")],
        "related_resources": [("Tech Stack Enrichment", "/enrichment/tech-stack-enrichment/"), ("Technographic Enrichment", "/enrichment/technographic-enrichment/"), ("Website Technology Enrichment", "/enrichment/website-technology-enrichment/")],
        "cta_headline": "Need to know what tools your prospects use?",
        "cta_text": "We'll enrich your target accounts with tech stack data so your reps know exactly what to pitch.",
    },
    {
        "slug": "territory-planning",
        "term": "Territory Planning",
        "meta_desc": "Territory planning divides your market among sales reps to maximize coverage and fairness. Learn how data quality determines whether territories work or create chaos.",
        "definition": '<p><strong>Territory planning</strong> divides your addressable market into segments assigned to individual sales reps or teams. Territories can be geographic (West Coast, Northeast), industry-based (healthcare, financial services), company-size based (SMB, mid-market, enterprise), or a combination. The goal is balanced workload, fair opportunity distribution, and complete market coverage so no accounts fall through the cracks.</p>',
        "why_matters": "<p>Territory planning runs on data. If company locations are wrong, geographic territories have gaps and overlaps. If industry classifications are inconsistent, vertical territories miss accounts. If company size data is missing, reps get assigned accounts that are too large or too small for their motion. Bad data turns a carefully designed territory plan into chaos within weeks as reps discover misassigned accounts and fight over ownership.</p>",
        "how_heading": "How to Build Data-Driven Territories",
        "how_items": [
            ("Clean the data first", "Standardize locations, company sizes, and industry classifications before drawing territory boundaries"),
            ("Size the opportunity", "Calculate the total addressable market in each territory to ensure balanced revenue potential"),
            ("Account assignment", "Use rules-based assignment (geography + size + industry) rather than manual cherry-picking"),
            ("Coverage analysis", "Identify white space in each territory where you have zero accounts or contacts"),
            ("Ongoing rebalancing", "Review territories quarterly as your market data updates, reps join/leave, and account compositions shift"),
        ],
        "example": "<p>A company divides the US into 8 territories by state groupings. Before data cleaning, 15% of accounts have wrong or missing state data. Territory 3 (Southeast) appears to have 40% more accounts than Territory 7 (Mountain West). After address validation and standardization, the real distribution is within 10% across all territories. Two reps who were overloaded get relief, and one underloaded rep gets reassigned accounts.</p>",
        "related_terms": [("Lead Routing", "lead-routing"), ("Market Sizing (TAM/SAM/SOM)", "market-sizing"), ("Data Standardization", "data-standardization")],
        "related_resources": [("Territory Planning Use Case", "/use-cases/territory-planning/"), ("Address Validation", "/validation/address-validation/"), ("Address Normalization", "/cleaning/address-normalization/")],
        "cta_headline": "Territory plan built on bad data?",
        "cta_text": "We'll clean your account data so territories are balanced, fair, and actually reflect where your market is.",
    },
]

if __name__ == "__main__":
    created = 0
    for t in TERMS:
        slug_dir = os.path.join(GLOSSARY_DIR, t["slug"])
        os.makedirs(slug_dir, exist_ok=True)
        html = generate_page(
            t["slug"], t["term"], t["meta_desc"], t["definition"],
            t["why_matters"], t["how_heading"], t["how_items"], t["example"],
            t["related_terms"], t["related_resources"], t["cta_headline"], t["cta_text"]
        )
        with open(os.path.join(slug_dir, "index.html"), "w") as f:
            f.write(html)
        created += 1
        print(f"  Created: glossary/{t['slug']}/index.html")
    print(f"\nBatch 3 complete: {created} glossary pages created.")
